# Generated by Django 5.1.4 on 2025-01-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_attendance_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
